// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD78S7QQLz6Jt6VLahY6wWO4yTBD6DSnEQ',
    appId: '1:1020768408737:web:4c6f62ef961dadac3dcce0',
    messagingSenderId: '1020768408737',
    projectId: 'hackthonacm',
    authDomain: 'hackthonacm.firebaseapp.com',
    storageBucket: 'hackthonacm.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGqYLeMgNrS6kJ_vSrE7TtrK76XBN4Rh0',
    appId: '1:1020768408737:android:f7ea063d54a22c783dcce0',
    messagingSenderId: '1020768408737',
    projectId: 'hackthonacm',
    storageBucket: 'hackthonacm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSgkBU94MrBPyQH4fujXjOlEMjO4iMpWQ',
    appId: '1:1020768408737:ios:469dd2996f3c449a3dcce0',
    messagingSenderId: '1020768408737',
    projectId: 'hackthonacm',
    storageBucket: 'hackthonacm.appspot.com',
    iosBundleId: 'com.example.flutterApplication3',
  );
}
